### ISSUE TITLE
Error pada html dan jquery undefined

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/personal-web#1]
dapat dilihat pada chrome dev tools
![image](https://user-images.githubusercontent.com/2832280/65225429-5505e780-daef-11e9-904d-a39df9e1bb0c.png)

solusi : 
- perhatikan penulisan <html> hanya boleh ada 1 `<html>`
- load script jquery sebelum load script-script lainnya

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/65240829-5f82aa00-db0c-11e9-98f8-70695088b4d6.png)
