### ISSUE TITLE
Portfolio cuma 1 dan Modal portfolio tidak muncul 

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/personal-web#2]
Ketika klik "tampilkan" modal tidak muncul
Mungkin ada kaitannya dengan issue #1 

Portfolio harus lebih dari 1, sehingga datanya dimasukkan ke PHP array

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/65240526-ac19b580-db0b-11e9-9114-684b7fe26776.png)
![image](https://user-images.githubusercontent.com/37020760/65240571-c5226680-db0b-11e9-95c9-da884643537c.png)
![image](https://user-images.githubusercontent.com/37020760/65240622-e4b98f00-db0b-11e9-9ddf-c058f26cd8f1.png)
![image](https://user-images.githubusercontent.com/37020760/65240709-192d4b00-db0c-11e9-8a51-edbf5ab0beae.png)
