### ISSUE TITLE
My skill selalu 0?

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/personal-web#3]
- untuk myskill tampilkan nilainya lebih dari 0
- tampilkan juga presentasenya berapa % sehingga pembaca bisa mengetahui nilai dari progress bar

![image](https://user-images.githubusercontent.com/2832280/65225820-ff7e0a80-daef-11e9-8264-a0bc66965bf7.png)

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/65240427-77a5f980-db0b-11e9-8472-e739ba07c9a7.png)
