### ISSUE TITLE
Class container kurang tepat

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/personal-web#4]
![image](https://user-images.githubusercontent.com/2832280/65226021-5b489380-daf0-11e9-9a4d-5330da7629fb.png)

- pada skill dan pendidikan baiknya pakai container
- footer baiknya tidak pakai container, sehingga tidak terlihat terpotong

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/65240260-0ebe8180-db0b-11e9-92f5-49f3549ba9ca.png)

![image](https://user-images.githubusercontent.com/37020760/65240337-357cb800-db0b-11e9-83c6-b4596f7adbb6.png)
