### ISSUE TITLE
Center text pada background image

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/personal-web#5]
![image](https://user-images.githubusercontent.com/2832280/65226297-d01bcd80-daf0-11e9-84c0-a1c183838a3c.png)

Untuk menampilkan text pada center baik vertical maupun horizontal, gunakan CSS, jangan `<br/>`

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/65239986-6c9e9980-db0a-11e9-9ffe-9592827163ce.png)
